name: doctors-reviews

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctors-reviews-api
    ports:
      - "9000:9000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 